#!/usr/bin/env python3
"""Generate Components/esp32-at/Inc/configuration.h from environment variables."""

from __future__ import annotations

import os
import sys
from pathlib import Path


def c_escape(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def require(name: str) -> str:
    value = os.environ.get(name, "").strip()
    if not value:
        print(f"error: {name} is required", file=sys.stderr)
        sys.exit(1)
    return value


def main() -> None:
    out = Path(
        sys.argv[1] if len(sys.argv) > 1 else "Components/esp32-at/Inc/configuration.h"
    )

    wifi_ssid = require("WIFI_SSID")
    wifi_pwd = require("WIFI_PWD")
    domain_name = require("DOMAIN_NAME")

    client_id = os.environ.get("CLIENT_ID", "").strip()
    if not client_id:
        client_id = os.environ.get("IOT_THING_NAME", "").strip()
    if not client_id:
        print("error: CLIENT_ID or IOT_THING_NAME is required", file=sys.stderr)
        sys.exit(1)

    utc_offset = os.environ.get("UTC_OFFSET", "-6").strip()
    mqtt_topic = os.environ.get("MQTT_TOPIC", "sensor/kitchen/data").strip()

    content = f"""#pragma once

/* Generated by scripts/generate-configuration.py — do not edit manually in CI. */

#define WIFI_SSID "{c_escape(wifi_ssid)}"
#define WIFI_PWD  "{c_escape(wifi_pwd)}"

#define UTC_OFFSET {utc_offset}
#define CLIENT_ID  "{c_escape(client_id)}"
#define DOMAIN_NAME "{c_escape(domain_name)}"

#define MQTT_TOPIC "{c_escape(mqtt_topic)}"

#define MQTT_PUBLISH_INTERVAL_MS 60000U
#define MQTT_QOS                 0U
#define MQTT_RETAIN              0U

#define ESP32_INIT_MAX_RETRIES     5U
#define ESP32_INIT_RETRY_DELAY_MS  500U
#define ESP32_AWS_MAX_RETRIES      3U

#define OTA_THING_NAME          CLIENT_ID
#define OTA_STREAM_TIMEOUT_MS   120000U
"""

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(content, encoding="utf-8")
    print(f"Wrote {out} (CLIENT_ID={client_id})")


if __name__ == "__main__":
    main()
